# Generated by Django 4.0.3 on 2022-03-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nac', models.DateField()),
                ('fam_list', models.CharField(max_length=40)),
                ('Edad', models.IntegerField()),
            ],
        ),
    ]
