# Generated by Django 4.0.3 on 2022-03-31 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfamili', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='Edad',
            new_name='edad',
        ),
    ]
